### PR TITLE
RIA-3701 postgresql 11 and feature flag switch

### PR DESCRIPTION
**Pull request by makowalski**
### JIRA link (if applicable) ###
[RIA-3701](https://tools.hmcts.net/jira/browse/RIA-3701)

### Change description ###
postgresql 11 and feature flag switch

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by makowalski** [comment]
Travis builds have long queue to process. Main Jenkins build is green, please conditionally review

**Review by mkayad — APPROVED** [review]
LGTM

**Review by bradsorour — DISMISSED** [review]
LGTM

**Review by tarun-palisetty — APPROVED** [review]
LGTM

**Pull request merged**
