### PR TITLE
RIA-6548: Fix import bug after rebase

### PR DESCRIPTION
**Pull request by neha-aggarw**

### CODE REVIEW

**Review by Ryan-Nesbitt — DISMISSED** [review]

**Review by colmlynch60 — DISMISSED** [review]
LGTM

**Review by Marcellofabbri — APPROVED** [review]
Looks fine to me

**Review by colmlynch60 — APPROVED** [review]
LGTM - I'm going to review the disabled tests

**Review by JamieHMCTS — APPROVED** [review]
LGTM

**Review by Ryan-Nesbitt — APPROVED** [review]

**Pull request merged**
