### PR TITLE
Ria 3683 ao lists reheard case

### PR DESCRIPTION
**Pull request by bradsorour**
### JIRA link (if applicable) ###

[RIA-3683](https://tools.hmcts.net/jira/browse/RIA-3683)

### Change description ###

See Jira

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by mkayad — DISMISSED** [review]
LGTM
Please resolve conflicts

**Review by mkayad — COMMENTED** [review]
Please resolve conflicts

**Review by Srihari-Nakkala — APPROVED** [review]
LGTM

**Review by makowalski — APPROVED** [review]
LGTM

**Pull request merged**
